---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-controller-minio
  labels:
    app.kubernetes.io/name: profiles-controller-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: profiles-controller-minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: profiles-controller-minio
    spec:
      serviceAccountName: profiles-controller-minio
      securityContext: {}
      containers:
        - name: profiles-controller-minio
          securityContext: {}
          image: "StatCan/profiles-controller:0.0.1"
          imagePullPolicy: IfNotPresent
          args:
            - minio
          resources: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profiles-controller-minio
  labels:
    app.kubernetes.io/name: profiles-controller-minio
rules:
  - apiGroups:
      - kubeflow.org
    resources:
      - profiles
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: profiles-controller-minio
  labels:
    app.kubernetes.io/name: profiles-controller-minio
subjects:
- kind: ServiceAccount
  name: profiles-controller-minio
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: profiles-controller-minio
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: profiles-controller-minio
  labels:
    app.kubernetes.io/name: profiles-controller-minio
