apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-gateway
  namespace: minio-system
spec:
  project: default
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 7.2.0
    helm:
      values: |
        ## MinIO(R) Gateway configuration
        nameOverride: "minio-gateway"
        gateway:
          enabled: true
          type: azure
          autoscaling:
            enabled: true
            minReplicas: "4"
            maxReplicas: "8"
          auth:
            azure:
              storageAccountNameExistingSecret: "azure-blob-storage"
              storageAccountNameExistingSecretKey: "storageAccountName"
              storageAccountKeyExistingSecret: "azure-blob-storage"
              storageAccountKeyExistingSecretKey: "storageAccountKey"
        extraEnv:
          - name: MINIO_ETCD_ENDPOINTS
            value: http://etcd-minio-gateway-headless:2379
        #image:
        #  registry: k8scc01covidacr.azurecr.io
        #  repository: minio/minio
        #  tag: 6379f1af
        ingress:
          enabled: false
          hostname: minio.local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
